### ISSUE TITLE
Generation of the same molecules

### ISSUE THREAD

**Issue by albertma-evotec** [robinlingwood/BIMODAL#1]
Hi,

I have tried sampling from the BIMODAL_random_512_aug_5 model. I noticed that it generated the extra same set of compounds every time I sampled it. Is it something it was supposed to do? I thought the model has some randomness like the REINVENT architecture. I am new to this area please excuse me as I probably do not fully understand your work.

Thanks
Albert

**Comment by robinlingwood** [comment]
Hi Albert,

If you delete line 17 in the model/sample.py and lines 10/11 in model/bimodal.py, you will generate different sets of compounds every time. We fixed the random seeds on purpose to get reproducible results. (For more information see also: https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState )  

Hope this information will be helpful,
Robin

**Comment by albertma-evotec** [comment]
Thank for the solution!
