### ISSUE TITLE
bidir_lstm.py BiDirLSTM object

### ISSUE THREAD

**Issue by albertma-evotec** [robinlingwood/BIMODAL#4]
in the forward function under the BiDirLSTM class, 
```
# out (sequence length, batch_size, 2 * hidden dim)
# Get last prediction from forward (0:hidden_dim) and backward direction (hidden_dim:2*hidden_dim)
for_out = out[-1, :, 0:self._hidden_dim]
back_out = out[0, :, self._hidden_dim:]
```
I thought it should be 
for_out = out[-1, :, self._hidden_dim:]
back_out = out[0, :, 0:self._hidden_dim]

as for_out is the last token in the sequence and the back_out is the first token in the sequence.
Or I am wrong about it? Sorry if I make a mistake about it.

Albert

**Comment by robinlingwood** [comment]
Hi Albert, 
I think the first dimension of the out tensor is equal to the sequence length. So we use the output of the forward lstm after the last token (-1) and the output of the backward lstm after the first token (0). The last dimension of the out tensor is equal to the number of hidden states, where the first half comes from the forward lstm and the second half from the backward lstm (https://pytorch.org/docs/stable/nn.html).

Hope this is helpful

**Comment by albertma-evotec** [comment]
Got it thanks!
